language: d
sudo: required
d:
 - ldc-1.1.0
before_install:
 - sudo add-apt-repository ppa:webupd8team/terminix -y
 - sudo apt-get update -q
 - sudo apt-get install gtkd libphobos2-ldc -y
script:
 - ./autogen.sh && ./configure && make
